// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: users_service/v1/models.proto

/* eslint-disable */
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "users_service.v1";

export interface User {
  id: string;
  name: string;
  email: string;
  company: string;
  is_verified: boolean;
  created_at: Timestamp | undefined;
  updated_at: Timestamp | undefined;
}

export const USERS_SERVICE_V1_PACKAGE_NAME = "users_service.v1";
