// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: users_service/v1/users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { User } from "./models";

export const protobufPackage = "users_service.v1";

export interface CreateUserRequest {
  name: string;
  email: string;
  company?: string | undefined;
}

export interface GetUserRequest {
  id: string;
}

export interface UpdateUserRequest {
  id: string;
  name?: string | undefined;
  email?: string | undefined;
  company?: string | undefined;
}

export interface ListUsersRequest {
  user_id: string;
  page_size: number;
  page_token: string;
}

export interface ListUsersResponse {
  data: User[];
  next_page_token: string;
  total_count: number;
  page_size: number;
  current_page: number;
  total_pages: number;
}

export interface DeleteUserRequest {
  id: string;
}

export interface DeleteUserResponse {
  success: boolean;
}

export const USERS_SERVICE_V1_PACKAGE_NAME = "users_service.v1";

export interface UsersServiceClient {
  createUser(request: CreateUserRequest): Observable<User>;

  getUser(request: GetUserRequest): Observable<User>;

  listUsers(request: ListUsersRequest): Observable<ListUsersResponse>;

  updateUser(request: UpdateUserRequest): Observable<User>;

  deleteUser(request: DeleteUserRequest): Observable<DeleteUserResponse>;
}

export interface UsersServiceController {
  createUser(request: CreateUserRequest): Promise<User> | Observable<User> | User;

  getUser(request: GetUserRequest): Promise<User> | Observable<User> | User;

  listUsers(request: ListUsersRequest): Promise<ListUsersResponse> | Observable<ListUsersResponse> | ListUsersResponse;

  updateUser(request: UpdateUserRequest): Promise<User> | Observable<User> | User;

  deleteUser(
    request: DeleteUserRequest,
  ): Promise<DeleteUserResponse> | Observable<DeleteUserResponse> | DeleteUserResponse;
}

export function UsersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUser", "getUser", "listUsers", "updateUser", "deleteUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "UsersService";
