// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: auth_service/v1/accounts.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Account } from "./models";

export const protobufPackage = "auth_service.v1";

export interface CreateAccountRequest {
  user_id: string;
  email: string;
  password: string;
}

export interface GetAccountRequest {
  user_id: string;
}

export interface UpdateAccountRequest {
  user_id: string;
  email?: string | undefined;
  password?: string | undefined;
  is_verified?: boolean | undefined;
  is_blocked?: boolean | undefined;
}

export interface ListAccountsRequest {
  user_id: string;
  page_size: number;
  page_token: string;
}

export interface ListAccountsResponse {
  data: Account[];
  next_page_token: string;
  total_count: number;
  page_size: number;
  current_page: number;
  total_pages: number;
}

export interface DeleteAccountRequest {
  user_id: string;
}

export interface DeleteAccountResponse {
  success: boolean;
}

export const AUTH_SERVICE_V1_PACKAGE_NAME = "auth_service.v1";

export interface AccountsServiceClient {
  createAccount(request: CreateAccountRequest): Observable<Account>;

  getAccount(request: GetAccountRequest): Observable<Account>;

  listAccounts(request: ListAccountsRequest): Observable<ListAccountsResponse>;

  updateAccount(request: UpdateAccountRequest): Observable<Account>;

  deleteAccount(request: DeleteAccountRequest): Observable<DeleteAccountResponse>;
}

export interface AccountsServiceController {
  createAccount(request: CreateAccountRequest): Promise<Account> | Observable<Account> | Account;

  getAccount(request: GetAccountRequest): Promise<Account> | Observable<Account> | Account;

  listAccounts(
    request: ListAccountsRequest,
  ): Promise<ListAccountsResponse> | Observable<ListAccountsResponse> | ListAccountsResponse;

  updateAccount(request: UpdateAccountRequest): Promise<Account> | Observable<Account> | Account;

  deleteAccount(
    request: DeleteAccountRequest,
  ): Promise<DeleteAccountResponse> | Observable<DeleteAccountResponse> | DeleteAccountResponse;
}

export function AccountsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createAccount", "getAccount", "listAccounts", "updateAccount", "deleteAccount"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AccountsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AccountsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ACCOUNTS_SERVICE_NAME = "AccountsService";
