// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: auth_service/v1/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { AuthenticatedResponse } from "./models";

export const protobufPackage = "auth_service.v1";

export interface SignInRequest {
  email: string;
  password: string;
}

export interface SignUpRequest {
  id: string;
  name: string;
  email: string;
  password: string;
  company?: string | undefined;
}

export const AUTH_SERVICE_V1_PACKAGE_NAME = "auth_service.v1";

export interface AuthServiceClient {
  signIn(request: SignInRequest): Observable<AuthenticatedResponse>;

  signUp(request: SignUpRequest): Observable<AuthenticatedResponse>;
}

export interface AuthServiceController {
  signIn(
    request: SignInRequest,
  ): Promise<AuthenticatedResponse> | Observable<AuthenticatedResponse> | AuthenticatedResponse;

  signUp(
    request: SignUpRequest,
  ): Promise<AuthenticatedResponse> | Observable<AuthenticatedResponse> | AuthenticatedResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["signIn", "signUp"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
