// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: auth_service/v1/models.proto

/* eslint-disable */
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "auth_service.v1";

export interface Account {
  user_id: string;
  email: string;
  password: string;
  is_verified: boolean;
  is_blocked: boolean;
  created_at: Timestamp | undefined;
  updated_at: Timestamp | undefined;
}

export interface User {
  id: string;
  name: string;
  email: string;
  company?: string | undefined;
}

export interface AuthenticatedResponse {
  user: User | undefined;
  token: string;
}

export const AUTH_SERVICE_V1_PACKAGE_NAME = "auth_service.v1";
