// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: outcomes_service/v1/actions.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "../../google/protobuf/timestamp";
import { Action } from "./models";

export const protobufPackage = "outcomes_service.v1";

export interface CreateActionRequest {
  title: string;
  user_id: string;
  outcome_id: string;
  driver_id: string;
  scheduled_for?: string | undefined;
  position?: number | undefined;
}

export interface GetActionRequest {
  id: string;
}

export interface UpdateActionRequest {
  id: string;
  title?: string | undefined;
  position?: number | undefined;
  outcome_id?: string | undefined;
  driver_id?: string | undefined;
  user_id?: string | undefined;
  completed_at?: Timestamp | undefined;
  scheduled_for?: Timestamp | undefined;
}

export interface ListActionsRequest {
  outcome_id: string;
  page_size: number;
  page_token: string;
}

export interface ListActionsResponse {
  data: Action[];
  next_page_token: string;
  total_count: number;
  page_size: number;
  current_page: number;
  total_pages: number;
}

export interface DeleteActionRequest {
  id: string;
}

export interface DeleteActionResponse {
  success: boolean;
}

export const OUTCOMES_SERVICE_V1_PACKAGE_NAME = "outcomes_service.v1";

export interface ActionsServiceClient {
  createAction(request: CreateActionRequest): Observable<Action>;

  getAction(request: GetActionRequest): Observable<Action>;

  listActions(request: ListActionsRequest): Observable<ListActionsResponse>;

  updateAction(request: UpdateActionRequest): Observable<Action>;

  deleteAction(request: DeleteActionRequest): Observable<DeleteActionResponse>;
}

export interface ActionsServiceController {
  createAction(request: CreateActionRequest): Promise<Action> | Observable<Action> | Action;

  getAction(request: GetActionRequest): Promise<Action> | Observable<Action> | Action;

  listActions(
    request: ListActionsRequest,
  ): Promise<ListActionsResponse> | Observable<ListActionsResponse> | ListActionsResponse;

  updateAction(request: UpdateActionRequest): Promise<Action> | Observable<Action> | Action;

  deleteAction(
    request: DeleteActionRequest,
  ): Promise<DeleteActionResponse> | Observable<DeleteActionResponse> | DeleteActionResponse;
}

export function ActionsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createAction", "getAction", "listActions", "updateAction", "deleteAction"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ActionsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ActionsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ACTIONS_SERVICE_NAME = "ActionsService";
