// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: outcomes_service/v1/drivers.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Driver } from "./models";

export const protobufPackage = "outcomes_service.v1";

export interface CreateDriverRequest {
  user_id: string;
  title: string;
  outcome_id: string;
  position?: number | undefined;
}

export interface GetDriverRequest {
  id: string;
}

export interface UpdateDriverRequest {
  id: string;
  title?: string | undefined;
}

export interface ListDriversRequest {
  user_id: string;
  page_size: number;
  page_token: string;
  outcome_id: string;
}

export interface ListDriversResponse {
  data: Driver[];
  next_page_token: string;
  total_count: number;
  page_size: number;
  current_page: number;
  total_pages: number;
}

export interface DeleteDriverRequest {
  id: string;
}

export interface DeleteDriverResponse {
  success: boolean;
}

export const OUTCOMES_SERVICE_V1_PACKAGE_NAME = "outcomes_service.v1";

export interface DriversServiceClient {
  createDriver(request: CreateDriverRequest): Observable<Driver>;

  getDriver(request: GetDriverRequest): Observable<Driver>;

  listDrivers(request: ListDriversRequest): Observable<ListDriversResponse>;

  updateDriver(request: UpdateDriverRequest): Observable<Driver>;

  deleteDriver(request: DeleteDriverRequest): Observable<DeleteDriverResponse>;
}

export interface DriversServiceController {
  createDriver(request: CreateDriverRequest): Promise<Driver> | Observable<Driver> | Driver;

  getDriver(request: GetDriverRequest): Promise<Driver> | Observable<Driver> | Driver;

  listDrivers(
    request: ListDriversRequest,
  ): Promise<ListDriversResponse> | Observable<ListDriversResponse> | ListDriversResponse;

  updateDriver(request: UpdateDriverRequest): Promise<Driver> | Observable<Driver> | Driver;

  deleteDriver(
    request: DeleteDriverRequest,
  ): Promise<DeleteDriverResponse> | Observable<DeleteDriverResponse> | DeleteDriverResponse;
}

export function DriversServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createDriver", "getDriver", "listDrivers", "updateDriver", "deleteDriver"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("DriversService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("DriversService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const DRIVERS_SERVICE_NAME = "DriversService";
