// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: outcomes_service/v1/focus.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Outcome } from "./models";

export const protobufPackage = "outcomes_service.v1";

export interface ActiveFocusDataRequest {
  user_id: string;
}

export interface ActiveFocusDataResponse {
  data: Outcome[];
}

export const OUTCOMES_SERVICE_V1_PACKAGE_NAME = "outcomes_service.v1";

export interface FocusServiceClient {
  getActiveFocusData(request: ActiveFocusDataRequest): Observable<ActiveFocusDataResponse>;
}

export interface FocusServiceController {
  getActiveFocusData(
    request: ActiveFocusDataRequest,
  ): Promise<ActiveFocusDataResponse> | Observable<ActiveFocusDataResponse> | ActiveFocusDataResponse;
}

export function FocusServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getActiveFocusData"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FocusService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FocusService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FOCUS_SERVICE_NAME = "FocusService";
