// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: outcomes_service/v1/models.proto

/* eslint-disable */
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "outcomes_service.v1";

export enum OutcomeStatus {
  UNSPECIFIED = 0,
  ACTIVE = 1,
  PARKED = 2,
  COMPLETED = 3,
  ABANDONED = 4,
  UNRECOGNIZED = -1,
}

export interface Outcome {
  id: string;
  user_id: string;
  title: string;
  why_it_matters: string;
  success_metric_value: number;
  success_metric_unit: string;
  deadline: Timestamp | undefined;
  status: OutcomeStatus;
  created_at: Timestamp | undefined;
  completed_at: Timestamp | undefined;
  archived_at: Timestamp | undefined;
  drivers: Driver[];
  tasks: Task[];
}

export interface Driver {
  id: string;
  title: string;
  outcome_id: string;
  position: number;
  created_at: Timestamp | undefined;
  tasks: Task[];
  outcome: Outcome | undefined;
}

export interface Task {
  id: string;
  driver_id: string;
  outcome_id: string;
  user_id: string;
  title: string;
  is_completed: boolean;
  created_at: Timestamp | undefined;
  updated_at: Timestamp | undefined;
  scheduled_for: Timestamp | undefined;
  last_moved_outcome_at: Timestamp | undefined;
  completed_at: Timestamp | undefined;
  outcome: Outcome | undefined;
  driver: Driver | undefined;
}

export const OUTCOMES_SERVICE_V1_PACKAGE_NAME = "outcomes_service.v1";
