// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: outcomes_service/v1/outcomes.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "../../google/protobuf/timestamp";
import { Outcome, OutcomeStatus } from "./models";

export const protobufPackage = "outcomes_service.v1";

export interface CreateOutcomeRequest {
  user_id: string;
  title: string;
  why_it_matters: string;
  deadline: Timestamp | undefined;
}

export interface GetOutcomeRequest {
  id: string;
}

export interface UpdateOutcomeRequest {
  id: string;
  title?: string | undefined;
  why_it_matters?: string | undefined;
  deadline?: Timestamp | undefined;
  status?: OutcomeStatus | undefined;
}

export interface ListOutcomesRequest {
  user_id: string;
  status?: OutcomeStatus | undefined;
  page_size: number;
  page_token: string;
}

export interface ListOutcomesResponse {
  data: Outcome[];
  next_page_token: string;
  total_count: number;
  page_size: number;
  current_page: number;
  total_pages: number;
}

export interface DeleteOutcomeRequest {
  id: string;
}

export interface DeleteOutcomeResponse {
  success: boolean;
}

export const OUTCOMES_SERVICE_V1_PACKAGE_NAME = "outcomes_service.v1";

export interface OutcomesServiceClient {
  createOutcome(request: CreateOutcomeRequest): Observable<Outcome>;

  getOutcome(request: GetOutcomeRequest): Observable<Outcome>;

  listOutcomes(request: ListOutcomesRequest): Observable<ListOutcomesResponse>;

  updateOutcome(request: UpdateOutcomeRequest): Observable<Outcome>;

  deleteOutcome(request: DeleteOutcomeRequest): Observable<DeleteOutcomeResponse>;
}

export interface OutcomesServiceController {
  createOutcome(request: CreateOutcomeRequest): Promise<Outcome> | Observable<Outcome> | Outcome;

  getOutcome(request: GetOutcomeRequest): Promise<Outcome> | Observable<Outcome> | Outcome;

  listOutcomes(
    request: ListOutcomesRequest,
  ): Promise<ListOutcomesResponse> | Observable<ListOutcomesResponse> | ListOutcomesResponse;

  updateOutcome(request: UpdateOutcomeRequest): Promise<Outcome> | Observable<Outcome> | Outcome;

  deleteOutcome(
    request: DeleteOutcomeRequest,
  ): Promise<DeleteOutcomeResponse> | Observable<DeleteOutcomeResponse> | DeleteOutcomeResponse;
}

export function OutcomesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOutcome", "getOutcome", "listOutcomes", "updateOutcome", "deleteOutcome"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OutcomesService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OutcomesService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const OUTCOMES_SERVICE_NAME = "OutcomesService";
