// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: outcomes_service/v1/success_metrics.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { SuccessMetric } from "./models";

export const protobufPackage = "outcomes_service.v1";

export interface CreateSuccessMetricRequest {
  outcome_id: string;
  metric_name: string;
  target_value: number;
  current_value?: number | undefined;
  unit: string;
  description?: string | undefined;
}

export interface GetSuccessMetricRequest {
  id: string;
}

export interface UpdateSuccessMetricRequest {
  id: string;
  metric_name?: string | undefined;
  target_value?: number | undefined;
  current_value?: number | undefined;
  unit?: string | undefined;
  description?: string | undefined;
}

export interface ListSuccessMetricsRequest {
  outcome_id: string;
  page_size: number;
  page_token: string;
}

export interface ListSuccessMetricsResponse {
  data: SuccessMetric[];
  next_page_token: string;
  total_count: number;
  page_size: number;
  current_page: number;
  total_pages: number;
}

export interface DeleteSuccessMetricRequest {
  id: string;
}

export interface DeleteSuccessMetricResponse {
  success: boolean;
}

export const OUTCOMES_SERVICE_V1_PACKAGE_NAME = "outcomes_service.v1";

export interface SuccessMetricsServiceClient {
  createSuccessMetric(request: CreateSuccessMetricRequest): Observable<SuccessMetric>;

  getSuccessMetric(request: GetSuccessMetricRequest): Observable<SuccessMetric>;

  listSuccessMetrics(request: ListSuccessMetricsRequest): Observable<ListSuccessMetricsResponse>;

  updateSuccessMetric(request: UpdateSuccessMetricRequest): Observable<SuccessMetric>;

  deleteSuccessMetric(request: DeleteSuccessMetricRequest): Observable<DeleteSuccessMetricResponse>;
}

export interface SuccessMetricsServiceController {
  createSuccessMetric(
    request: CreateSuccessMetricRequest,
  ): Promise<SuccessMetric> | Observable<SuccessMetric> | SuccessMetric;

  getSuccessMetric(
    request: GetSuccessMetricRequest,
  ): Promise<SuccessMetric> | Observable<SuccessMetric> | SuccessMetric;

  listSuccessMetrics(
    request: ListSuccessMetricsRequest,
  ): Promise<ListSuccessMetricsResponse> | Observable<ListSuccessMetricsResponse> | ListSuccessMetricsResponse;

  updateSuccessMetric(
    request: UpdateSuccessMetricRequest,
  ): Promise<SuccessMetric> | Observable<SuccessMetric> | SuccessMetric;

  deleteSuccessMetric(
    request: DeleteSuccessMetricRequest,
  ): Promise<DeleteSuccessMetricResponse> | Observable<DeleteSuccessMetricResponse> | DeleteSuccessMetricResponse;
}

export function SuccessMetricsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createSuccessMetric",
      "getSuccessMetric",
      "listSuccessMetrics",
      "updateSuccessMetric",
      "deleteSuccessMetric",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SuccessMetricsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SuccessMetricsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SUCCESS_METRICS_SERVICE_NAME = "SuccessMetricsService";
