// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: boardsservice.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "boardsservice";

export interface PaginationDto {
  page: number;
  skip: number;
}

export interface UpdateBoardDto {
  id: string;
  title: string;
}

export interface FindOneBoardDto {
  id: string;
}

export interface Empty {
}

export interface Boards {
  boards: Board[];
}

export interface CreateBoardDto {
  title: string;
}

export interface Board {
  id: string;
  title: string;
}

export const BOARDSSERVICE_PACKAGE_NAME = "boardsservice";

export interface BoardsServiceClient {
  createBoard(request: CreateBoardDto): Observable<Board>;

  findAllBoards(request: Empty): Observable<Boards>;

  findOneBoard(request: FindOneBoardDto): Observable<Board>;

  updateBoard(request: UpdateBoardDto): Observable<Board>;

  removeBoard(request: FindOneBoardDto): Observable<Board>;

  queryBoards(request: Observable<PaginationDto>): Observable<Boards>;
}

export interface BoardsServiceController {
  createBoard(request: CreateBoardDto): Promise<Board> | Observable<Board> | Board;

  findAllBoards(request: Empty): Promise<Boards> | Observable<Boards> | Boards;

  findOneBoard(request: FindOneBoardDto): Promise<Board> | Observable<Board> | Board;

  updateBoard(request: UpdateBoardDto): Promise<Board> | Observable<Board> | Board;

  removeBoard(request: FindOneBoardDto): Promise<Board> | Observable<Board> | Board;

  queryBoards(request: Observable<PaginationDto>): Observable<Boards>;
}

export function BoardsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createBoard", "findAllBoards", "findOneBoard", "updateBoard", "removeBoard"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("BoardsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = ["queryBoards"];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("BoardsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BOARDS_SERVICE_NAME = "BoardsService";
