// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: proto/outcomes.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "outcomes.v1";

export enum OutcomeStatus {
  /** OUTCOME_STATUS_UNSPECIFIED - Required */
  OUTCOME_STATUS_UNSPECIFIED = 0,
  OUTCOME_STATUS_ACTIVE = 1,
  OUTCOME_STATUS_PARKED = 2,
  OUTCOME_STATUS_COMPLETED = 3,
  OUTCOME_STATUS_ABANDONED = 4,
  UNRECOGNIZED = -1,
}

export interface Outcome {
  id: string;
  /** changed from userId */
  userId: string;
  title: string;
  whyItMatters: string;
  successMetricValue: number;
  successMetricUnit: string;
  deadline: Timestamp | undefined;
  status: OutcomeStatus;
  createdAt: Timestamp | undefined;
  completedAt: Timestamp | undefined;
  archivedAt: Timestamp | undefined;
  drivers: Driver[];
  tasks: Task[];
}

export interface Driver {
  id: string;
  title: string;
  outcomeId: string;
  position: number;
  createdAt: Timestamp | undefined;
  tasks: Task[];
  outcome: Outcome | undefined;
}

export interface Task {
  id: string;
  driverId: string;
  outcomeId: string;
  userId: string;
  title: string;
  isCompleted: boolean;
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
  scheduledFor: Timestamp | undefined;
  lastMovedOutcomeAt: Timestamp | undefined;
  completedAt: Timestamp | undefined;
  outcome: Outcome | undefined;
  driver: Driver | undefined;
}

export interface CreateOutcomeRequest {
  userId: string;
  title: string;
  whyItMatters: string;
  successMetricValue: number;
  successMetricUnit: string;
  deadline: Timestamp | undefined;
}

export interface GetOutcomeRequest {
  id: string;
}

export interface UpdateOutcomeRequest {
  id: string;
  title?: string | undefined;
  whyItMatters?: string | undefined;
  successMetricValue?: number | undefined;
  successMetricUnit?: string | undefined;
  deadline?: Timestamp | undefined;
  status?: OutcomeStatus | undefined;
}

export interface ListOutcomesRequest {
  userId: string;
  status?: OutcomeStatus | undefined;
  pageSize: number;
  pageToken: string;
}

export interface ListOutcomesResponse {
  outcomes: Outcome[];
  nextPageToken: string;
  totalCount: number;
}

export interface DeleteOutcomeRequest {
  id: string;
}

export interface DeleteOutcomeResponse {
  success: boolean;
}

export const OUTCOMES_V1_PACKAGE_NAME = "outcomes.v1";

export interface OutcomeServiceClient {
  createOutcome(request: CreateOutcomeRequest): Observable<Outcome>;

  getOutcome(request: GetOutcomeRequest): Observable<Outcome>;

  updateOutcome(request: UpdateOutcomeRequest): Observable<Outcome>;

  deleteOutcome(request: DeleteOutcomeRequest): Observable<DeleteOutcomeResponse>;

  listOutcomes(request: ListOutcomesRequest): Observable<ListOutcomesResponse>;
}

export interface OutcomeServiceController {
  createOutcome(request: CreateOutcomeRequest): Promise<Outcome> | Observable<Outcome> | Outcome;

  getOutcome(request: GetOutcomeRequest): Promise<Outcome> | Observable<Outcome> | Outcome;

  updateOutcome(request: UpdateOutcomeRequest): Promise<Outcome> | Observable<Outcome> | Outcome;

  deleteOutcome(
    request: DeleteOutcomeRequest,
  ): Promise<DeleteOutcomeResponse> | Observable<DeleteOutcomeResponse> | DeleteOutcomeResponse;

  listOutcomes(
    request: ListOutcomesRequest,
  ): Promise<ListOutcomesResponse> | Observable<ListOutcomesResponse> | ListOutcomesResponse;
}

export function OutcomeServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOutcome", "getOutcome", "updateOutcome", "deleteOutcome", "listOutcomes"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OutcomeService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OutcomeService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const OUTCOME_SERVICE_NAME = "OutcomeService";
