// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: outcomes.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "outcomes.v1";

export enum OutcomeStatus {
  OUTCOME_STATUS_UNSPECIFIED = 0,
  OUTCOME_STATUS_ACTIVE = 1,
  OUTCOME_STATUS_PARKED = 2,
  OUTCOME_STATUS_COMPLETED = 3,
  OUTCOME_STATUS_ABANDONED = 4,
  UNRECOGNIZED = -1,
}

export interface Outcome {
  id: string;
  user_id: string;
  title: string;
  why_it_matters: string;
  success_metric_value: number;
  success_metric_unit: string;
  deadline: Timestamp | undefined;
  status: OutcomeStatus;
  created_at: Timestamp | undefined;
  completed_at: Timestamp | undefined;
  archived_at: Timestamp | undefined;
  drivers: Driver[];
  tasks: Task[];
}

export interface Driver {
  id: string;
  title: string;
  outcome_id: string;
  position: number;
  created_at: Timestamp | undefined;
  tasks: Task[];
  outcome: Outcome | undefined;
}

export interface Task {
  id: string;
  driver_id: string;
  outcome_id: string;
  user_id: string;
  title: string;
  is_completed: boolean;
  created_at: Timestamp | undefined;
  updated_at: Timestamp | undefined;
  scheduled_for: Timestamp | undefined;
  last_moved_outcome_at: Timestamp | undefined;
  completed_at: Timestamp | undefined;
  outcome: Outcome | undefined;
  driver: Driver | undefined;
}

export interface CreateOutcomeRequest {
  user_id: string;
  title: string;
  why_it_matters: string;
  success_metric_value: number;
  success_metric_unit: string;
  deadline: Timestamp | undefined;
}

export interface GetOutcomeRequest {
  id: string;
}

export interface UpdateOutcomeRequest {
  id: string;
  title?: string | undefined;
  why_it_matters?: string | undefined;
  success_metric_value?: number | undefined;
  success_metric_unit?: string | undefined;
  deadline?: Timestamp | undefined;
  status?: OutcomeStatus | undefined;
}

export interface ListOutcomesRequest {
  user_id: string;
  status?: OutcomeStatus | undefined;
  page_size: number;
  page_token: string;
}

export interface ListOutcomesResponse {
  data: Outcome[];
  next_page_token: string;
  total_count: number;
  page_size: number;
  current_page: number;
  total_pages: number;
}

export interface DeleteOutcomeRequest {
  id: string;
}

export interface DeleteOutcomeResponse {
  success: boolean;
}

export interface CreateDriverRequest {
  user_id: string;
  title: string;
  outcome_id: string;
  position?: number | undefined;
}

export interface GetDriverRequest {
  id: string;
}

export interface UpdateDriverRequest {
  id: string;
  title?: string | undefined;
}

export interface ListDriversRequest {
  user_id: string;
  page_size: number;
  page_token: string;
}

export interface ListDriversResponse {
  data: Driver[];
  next_page_token: string;
  total_count: number;
  page_size: number;
  current_page: number;
  total_pages: number;
}

export interface DeleteDriverRequest {
  id: string;
}

export interface DeleteDriverResponse {
  success: boolean;
}

export const OUTCOMES_V1_PACKAGE_NAME = "outcomes.v1";

export interface OutcomeServiceClient {
  createOutcome(request: CreateOutcomeRequest): Observable<Outcome>;

  getOutcome(request: GetOutcomeRequest): Observable<Outcome>;

  updateOutcome(request: UpdateOutcomeRequest): Observable<Outcome>;

  deleteOutcome(request: DeleteOutcomeRequest): Observable<DeleteOutcomeResponse>;

  listOutcomes(request: ListOutcomesRequest): Observable<ListOutcomesResponse>;

  createDriver(request: CreateDriverRequest): Observable<Driver>;

  getDriver(request: GetDriverRequest): Observable<Driver>;

  updateDriver(request: UpdateDriverRequest): Observable<Driver>;

  deleteDriver(request: DeleteDriverRequest): Observable<DeleteDriverResponse>;

  listDrivers(request: ListDriversRequest): Observable<ListDriversResponse>;
}

export interface OutcomeServiceController {
  createOutcome(request: CreateOutcomeRequest): Promise<Outcome> | Observable<Outcome> | Outcome;

  getOutcome(request: GetOutcomeRequest): Promise<Outcome> | Observable<Outcome> | Outcome;

  updateOutcome(request: UpdateOutcomeRequest): Promise<Outcome> | Observable<Outcome> | Outcome;

  deleteOutcome(
    request: DeleteOutcomeRequest,
  ): Promise<DeleteOutcomeResponse> | Observable<DeleteOutcomeResponse> | DeleteOutcomeResponse;

  listOutcomes(
    request: ListOutcomesRequest,
  ): Promise<ListOutcomesResponse> | Observable<ListOutcomesResponse> | ListOutcomesResponse;

  createDriver(request: CreateDriverRequest): Promise<Driver> | Observable<Driver> | Driver;

  getDriver(request: GetDriverRequest): Promise<Driver> | Observable<Driver> | Driver;

  updateDriver(request: UpdateDriverRequest): Promise<Driver> | Observable<Driver> | Driver;

  deleteDriver(
    request: DeleteDriverRequest,
  ): Promise<DeleteDriverResponse> | Observable<DeleteDriverResponse> | DeleteDriverResponse;

  listDrivers(
    request: ListDriversRequest,
  ): Promise<ListDriversResponse> | Observable<ListDriversResponse> | ListDriversResponse;
}

export function OutcomeServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createOutcome",
      "getOutcome",
      "updateOutcome",
      "deleteOutcome",
      "listOutcomes",
      "createDriver",
      "getDriver",
      "updateDriver",
      "deleteDriver",
      "listDrivers",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OutcomeService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OutcomeService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const OUTCOME_SERVICE_NAME = "OutcomeService";
