-- AlterTable
ALTER TABLE "issues" ALTER COLUMN "order" DROP DEFAULT,
ALTER COLUMN "order" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "lists" ALTER COLUMN "order" DROP DEFAULT,
ALTER COLUMN "order" SET DATA TYPE TEXT;
